### ISSUE TITLE
Use cases for different storage methods?

### ISSUE THREAD

**Issue by newlegendmedia** [MacFJA/svelte-persistent-store#14]
I have a SvelteKit app that I need to persist what I see as two different kinds of user state...

1) Auth State: I am currently using an http only cookie to persist an authentication token and that seems to be working, though Im not sure about security issues of having that token visible in the browser cookies inspector.

2) User App State: I need to persist some user settings such as the current "space" or "page" they are using in the app, as they can have multiple workspaces and pages. I am not sure whether this would best be stored in one of the various local storage options, one of the various cookie type options, or something else etc.

Any suggestions?  

Thanks!

**Comment by MacFJA** [comment]
> 1. Auth State: I am currently using an http only cookie to persist an authentication token and that seems to be working, though Im not sure about security issues of having that token visible in the browser cookies inspector.

For the authentication token, you have several options:
- A `cookie`, that will be transparent for you, as they can easily be send and receive with HTTP request. (But keep in mind that this lib don't have (yet?) built-in storage for **server `cookie`**, meaning that you have to implement your own way to read cookie at server side)
- An item in `localStorage`/`sessionStorage`: you will need to get the token from the authentication, store it. Then when you need to call you API/pages you will have to read the storage and pass the data to the request (in most of case through a custom header)

Concerning the security issue, it depend of the kind of token, a JWT token can have a signature that ensure the token is not forged, and signature can be user specific (instead of application specific).
But like any application, the cookie should not store clear personal and critical information, and like for any application if cookies are stolen, impersonation can be done.
If security concern is an import part of you application, you should set the TTL of the token short, and store it (at browser side) in temporary/short live storage, like `sessionStorage` or session `cookies`

----

> 2\. User App State: I need to persist some user settings such as the current "space" or "page" they are using in the app, as they can have multiple workspaces and pages. I am not sure whether this would best be stored in one of the various local storage options, one of the various cookie type options, or something else etc.

Depending of the size of the data to store, cookie or browser storage can be used:
- Cookie are not meant to store lots of data (as there are sent to every request's headers)
- Browser storage only exist at browser side and the server don't know them (except if you explicitly setup your app to send them)

For the kind of storage, you have 2 kind:
- temporary (browsing session)
- "long term"

The temporary storage are:
- `sessionStorage` (only in browser): when the browser is closed, everything in `sessionStorage` is deleted
- Session `cookie` (available in browser* and server): when the browser is closed, all session `cookies` are removed

The "long term" storage are:
- `localStorage` (only in browser): depending of the browser policies, this storage can have a maximum capacity per website/domain/etc. and maybe some purge strategy if the capacity is exceed.
- `cookie` (available in browser* and server): The cookies have a limited size, there is not defined limit, but 4kB seem to by the most common limit
- `IndexedDB` (only in browser): depending of the browser policies, this storage can have a maximum capacity per website/domain/etc. and maybe some purge strategy if the capacity is exceed.

*About cookies in browser: For cookie to be accessible in browser, the `httponly` flag need to be disabled. But it will expose the cookie to any JavaScript code and then potentially expose personal/critical data.

----

And for the mix use of storage type, you can do it. Further more you should do it if you have different kind of scope.
For example storing the user theme should be in `localStorage` (as it need to be keep between browsing session, but it's not the end of the world if the data is loose), but storing user last action/visited page, `sessionStorage` is more than enough as the information don't hold lots of meaning in future browsing.
There are lots of different use case, and storage depend on them. But you should not limit yourself to use only one storage as it can restrict features/functionality of one use case.

----

I hope that answers your questions, if not, don't hesitate to ask more :wink:
