### ISSUE TITLE
Disable warnings not working

### ISSUE THREAD

**Issue by Carlos-err406** [MacFJA/svelte-persistent-store#56]
i get this logs on every server restart and is getting quite annoying, i tried to use the disableWarnings function but nothing changes.

```
Unable to find the document.cookies. No data will be persisted.
Are you running on a server? Most of storages are not available while running on a server.      
Unable to find the window.localStorage. No data will be persisted.
Are you running on a server? Most of storages are not available while running on a server.      
Unable to find the window.sessionStorage. No data will be persisted.
Are you running on a server? Most of storages are not available while running on a server.
```
am i using it wrong? 
![image](https://github.com/MacFJA/svelte-persistent-store/assets/81443707/a29111ba-5fdd-40df-aa96-adf95013f5f4)

**Comment by MacFJA** [comment]
It's not your fault.

It's bug that have been introduced in version `2.3.0`: the new alias functions (`persistCookie`, `persistBrowserSession`, `persistBrowserLocal` and theirs derivate function) use centralized storage. But this storage is created because you can have the chances to call `disableWarnings()`

I will update the code so those centralized storage are lazy-created

**Comment by MacFJA** [comment]
@Carlos-err406 I just publish the version `2.4.1` that fix the issue.

**Comment by Carlos-err406** [comment]
looks good to me, thanks!
