### ISSUE TITLE
Store string without quote

### ISSUE THREAD

**Issue by ffvpor** [MacFJA/svelte-persistent-store#6]
Hello

I want to store a token returned by a python API in a persistent store. The function returns a token without quotes. If I use the native function ```localStorage.setItem```, it ok but if I use ```sessionToken.set```, the token value is surrounded by quotes, then using token produces error. I can't figure out where my mistake is ! 

![localStorageQuote](https://user-images.githubusercontent.com/7997719/120618157-14810580-c45b-11eb-8663-ae51422116b7.png)

Any advice to help me?
Thanks!
 
```javascript
...
      const response = await authAPI.authGetToken(email, password);
      const token = response.data.token
      if (token) {
          sessionToken.set(token); // store with quote
          // or sessionToken.set(response.data.token);
          localStorage.setItem('token', token) // store without quote
```

```javascript
// store.js
import {persist, localStorage} from '@macfja/svelte-persistent-store';
import {writable} from 'svelte/store';
export let sessionToken = persist(writable(''), localStorage(), 'userToken')
```

**Comment by MacFJA** [comment]
Hi,

The issue is not on your side.
It's way data is saved with the lib.

To be able to save most of possible data, the data is converted in a JSON compatible string.
so everything goes through a `JSON.stringify` when saved and a `JSON.parse` when read.

----

The data saved in the localStorage is not really mean to be accessed without using the store.

If you really need to read and write the localStorage without using the store, the best/quickest solution that I can think of is to create a custom `StorageInterface` that don't touch in input data:
```js
function stringLocalstorage(): StorageInterface<string> {
    return {
        getValue(key: string): string | null {
            return localStorage.getItem(key)
        },
        deleteValue(key: string) {
            localStorage.removeItem(key)
        },
        setValue(key: string, value: string) {
            localStorage.setItem(key, value)
        }
    }
}

export let sessionToken = persist(writable(''), stringLocalstorage(), 'userToken')
```
But be careful, by modifying the localStorage directly (without the store), the store won't be notified of external changes.
If you only do reading you are good to go, but writing can create unexpected behavior

**Comment by ffvpor** [comment]
Thank you for this clear and detailed explanation. I appreciate too  the proposed solution.
All I have to do is update my code :smile:
